### ISSUE TITLE
omegaconf.errors.MissingMandatoryValue: Missing mandatory value: model.backbone.ignore_last_stride

### ISSUE THREAD

**Issue by Hisssec** [philip-mueller/wsrpn#2]
Hi, I have a bug, can you help me solve it? thx
/home/hash/anaconda3/envs/wsrpn/bin/python -X pycache_prefix=/home/hash/.cache/JetBrains/PyCharm2024.1/cpython-cache /home/hash/pycharm-2023.2/plugins/python/helpers/pydev/pydevd.py --multiprocess --qt-support=auto --client 127.0.0.1 --port 35839 --file /media/hash/data/code/wsrpn-main/src/train.py 
已连接到 pydev 调试器(内部版本号 241.18034.82)[2024-08-12 20:41:21,753][__main__][INFO] - Loading data from /media/hash/data/code/wsrpn-main/datasets/CXR8
Error executing job with overrides: []
Error executing job with overrides: []
Traceback (most recent call last):
  File "/home/hash/anaconda3/envs/wsrpn/lib/python3.9/site-packages/omegaconf/dictconfig.py", line 367, in __getitem__
    return self._get_impl(key=key, default_value=_DEFAULT_MARKER_)
  File "/home/hash/anaconda3/envs/wsrpn/lib/python3.9/site-packages/omegaconf/dictconfig.py", line 445, in _get_impl
    return self._resolve_with_default(
  File "/home/hash/anaconda3/envs/wsrpn/lib/python3.9/site-packages/omegaconf/basecontainer.py", line 63, in _resolve_with_default
    raise MissingMandatoryValue("Missing mandatory value: $FULL_KEY")
omegaconf.errors.MissingMandatoryValue: Missing mandatory value: $FULL_KEY

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/hash/anaconda3/envs/wsrpn/lib/python3.9/site-packages/hydra/_internal/utils.py", line 377, in _run_hydra
    run_and_report(
  File "/home/hash/anaconda3/envs/wsrpn/lib/python3.9/site-packages/hydra/_internal/utils.py", line 214, in run_and_report
    raise ex
  File "/home/hash/anaconda3/envs/wsrpn/lib/python3.9/site-packages/hydra/_internal/utils.py", line 211, in run_and_report
    return func()
  File "/home/hash/anaconda3/envs/wsrpn/lib/python3.9/site-packages/hydra/_internal/utils.py", line 378, in <lambda>
    lambda: hydra.run(
  File "/home/hash/anaconda3/envs/wsrpn/lib/python3.9/site-packages/hydra/_internal/hydra.py", line 111, in run
    _ = ret.return_value
  File "/home/hash/anaconda3/envs/wsrpn/lib/python3.9/site-packages/hydra/core/utils.py", line 233, in return_value
    raise self._return_value
  File "/home/hash/pycharm-2023.2/plugins/python/helpers/pydev/_pydevd_bundle/pydevd_comm.py", line 1565, in do_it
    result = pydevd_vars.evaluate_expression(self.thread_id, self.frame_id, self.expression, self.doExec)
  File "/home/hash/pycharm-2023.2/plugins/python/helpers/pydev/_pydevd_bundle/pydevd_vars.py", line 461, in evaluate_expression
    return eval_func(expression, updated_globals, frame, doExec, get_eval_exception_msg)
  File "/home/hash/pycharm-2023.2/plugins/python/helpers-pro/pydevd_asyncio/pydevd_asyncio_utils.py", line 93, in _eval_async_expression
    result = exec_async_code(compiled, global_names)
  File "/home/hash/pycharm-2023.2/plugins/python/helpers-pro/pydevd_asyncio/pydevd_asyncio_utils.py", line 117, in _exec_async_code
    result = func()
  File "<string>", line 1, in <module>
  File "/home/hash/anaconda3/envs/wsrpn/lib/python3.9/site-packages/hydra/core/utils.py", line 233, in return_value
    raise self._return_value
  File "/home/hash/anaconda3/envs/wsrpn/lib/python3.9/site-packages/hydra/core/utils.py", line 160, in run_job
    ret.return_value = task_function(task_cfg)
  File "/media/hash/data/code/wsrpn-main/src/train.py", line 581, in run_training
    wandb_run_api_path, results = train(config)
  File "/media/hash/data/code/wsrpn-main/src/train.py", line 164, in train
    model: ObjectDetectorModelInterface = load_model_from_config(config.model)
  File "/media/hash/data/code/wsrpn-main/src/model/model_loader.py", line 39, in load_model_from_config
    config = prepare_config(config, model_cls.CONFIG_CLS, log)
  File "/media/hash/data/code/wsrpn-main/src/utils/utils.py", line 24, in prepare_config
    diff = DeepDiff(config, new_config, verbose_level=2)
  File "/home/hash/anaconda3/envs/wsrpn/lib/python3.9/site-packages/deepdiff/diff.py", line 324, in __init__
    self._diff(root, parents_ids=frozenset({id(t1)}), _original_type=_original_type)
  File "/home/hash/anaconda3/envs/wsrpn/lib/python3.9/site-packages/deepdiff/diff.py", line 1634, in _diff
    self._diff_dict(level, parents_ids, local_tree=local_tree)
  File "/home/hash/anaconda3/envs/wsrpn/lib/python3.9/site-packages/deepdiff/diff.py", line 628, in _diff_dict
    self._diff(next_level, parents_ids_added, local_tree=local_tree)
  File "/home/hash/anaconda3/envs/wsrpn/lib/python3.9/site-packages/deepdiff/diff.py", line 1634, in _diff
    self._diff_dict(level, parents_ids, local_tree=local_tree)
  File "/home/hash/anaconda3/envs/wsrpn/lib/python3.9/site-packages/deepdiff/diff.py", line 615, in _diff_dict
    item_id = id(t1[key1])
  File "/home/hash/anaconda3/envs/wsrpn/lib/python3.9/site-packages/omegaconf/dictconfig.py", line 373, in __getitem__
    self._format_and_raise(key=key, value=None, cause=e)
  File "/home/hash/anaconda3/envs/wsrpn/lib/python3.9/site-packages/omegaconf/base.py", line 190, in _format_and_raise
    format_and_raise(
  File "/home/hash/anaconda3/envs/wsrpn/lib/python3.9/site-packages/omegaconf/_utils.py", line 821, in format_and_raise
    _raise(ex, cause)
  File "/home/hash/anaconda3/envs/wsrpn/lib/python3.9/site-packages/omegaconf/_utils.py", line 719, in _raise
    raise ex.with_traceback(sys.exc_info()[2])  # set end OC_CAUSE=1 for full backtrace
  File "/home/hash/anaconda3/envs/wsrpn/lib/python3.9/site-packages/omegaconf/dictconfig.py", line 367, in __getitem__
    return self._get_impl(key=key, default_value=_DEFAULT_MARKER_)
  File "/home/hash/anaconda3/envs/wsrpn/lib/python3.9/site-packages/omegaconf/dictconfig.py", line 445, in _get_impl
    return self._resolve_with_default(
  File "/home/hash/anaconda3/envs/wsrpn/lib/python3.9/site-packages/omegaconf/basecontainer.py", line 63, in _resolve_with_default
    raise MissingMandatoryValue("Missing mandatory value: $FULL_KEY")
omegaconf.errors.MissingMandatoryValue: Missing mandatory value: model.backbone.ignore_last_stride
    full_key: model.backbone.ignore_last_stride
    reference_type=BackboneConfig
    object_type=BackboneConfig

进程已结束，退出代码为 1

**Comment by philip-mueller** [comment]
The ignore_last_stride parameters was missing in the backbone config. 
I have now added it with the default value false (as in the paper). 
Now it should work. Could you please try again and let me know whether this solved your issue?

**Comment by Hisssec** [comment]
thx,I success it
